FROM node:22-alpine as builder

WORKDIR /app

COPY client/package*.json ./

RUN npm install

COPY client/ ./

ENV REACT_APP_API_URL=https://yentaconnect.com/api

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
